backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "galeria"
    label: "Galería"
    folder: "content/galeria"
    create: true
    fields:
      - { name: "titulo", label: "Título", widget: "string" }
      - { name: "imagen", label: "Imagen", widget: "image" }
